// frontend-react/vector-db-demo/src/app/movies/page.tsx
"use client";

import { axiosClient } from "@/api/axios-client";
import { usePostApiV1MoviesSearch } from "@/api/generated/movies/movies";
import RecommendedSearchCard from "@/components/movies/recommended-search-card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ArrowRightIcon } from "lucide-react";
import { useEffect, useState } from "react";

const mockMovieSearches = [
  "Intense action with lots of explosions and car chases",
  "A movie about the future",
  "Underdog sports team overcoming impossible odds",
  "Comedy about a group of friends",
];

export default function Movies() {
  const [searchValue, setSearchValue] = useState("");

  const { mutate, isLoading, data, error } = usePostApiV1MoviesSearch();

  const handleSearch = () => {
    if (!searchValue) return;
    mutate({ data: { search: searchValue } });
  };

  useEffect(() => {
    console.log("data", data);
  }, [data]);
  return (
    <div className="flex flex-col min-h-screen">
      {/* <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60"></header> */}

      <main className="flex-1 container py-6">
        <div className="max-w-4xl mx-auto space-y-4">
          <div className="text-center space-y-2">
            <h1 className="text-4xl font-bold">Vector Movie Search</h1>
          </div>
          <div className="text-center space-y-4"></div>

          {/* Search Interface */}
          <div className="relative bg-[#fafafa] flex h-40  rounded-xl border-gray-900 border-t-0 border-b-0">
            <Textarea
              className="h-full resize-none text-black/80 placeholder:text-black/60 rounded-xl"
              placeholder="Describe the movie you want to watch..."
              value={searchValue}
              onChange={(e) => setSearchValue(e.target.value)}
            />
            <Button
              size="icon"
              className="rounded-full absolute bottom-3 right-3 cursor-pointer"
              onClick={handleSearch}
            >
              <ArrowRightIcon className="h-6 w-6" />
            </Button>
          </div>

          {/* Recommended Prompts */}
          <div className="flex flex-row items-center justify-evenly flex-wrap h-6 gap-y-2">
            {mockMovieSearches.map((search, index) => (
              <RecommendedSearchCard
                key={index}
                searchValue={search}
                onClick={() => setSearchValue(search)}
              />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

// frontend-angular/src/app/features/movies/pages/movies/movies.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { BadgeComponent } from '../../../../shared/components/badge.component';
import { MovieSearchComponent } from '../../components/search/movie-search.component';
import { Movie, MoviesService } from '../../../../api';
import { MovieCardComponent } from '../../components/movie-card/movie-card.component';
import { MovieSearchService } from '../../services/movie-search.service';

@Component({
  selector: 'app-movies',
  templateUrl: './movies.component.html',
  imports: [BadgeComponent, MovieSearchComponent, MovieCardComponent],
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MoviesPage {
  constructor(
    private movieService: MoviesService,
    private movieSearchService: MovieSearchService
  ) {}

  mockMovieSearches = [
    'Intense action with lots of explosions and car chases',
    'A movie about the future',
    'Underdog sports team overcoming impossible odds',
    'Comedy about a group of friends',
  ];
  searchValue: string = '';

  isLoading = false;
  movies: Movie[] = [];

  handleSearch(value: string) {
    if (!value) return;
    this.isLoading = true;
    this.movies = [];

    this.movieService.apiV1MoviesSearchPost({ search: value }).subscribe({
      next: (movies) => {
        this.movies = movies;
        this.movieSearchService.setSearch(value, movies);
        this.isLoading = false;
      },
      error: (err) => {
        console.error('Error fetching movies', err);
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    // Restore previous search state if available
    this.searchValue = this.movieSearchService.searchValue;
    this.movies = this.movieSearchService.searchResults;
  }
}

<div class="flex flex-col items-center min-h-screen bg-white">
  <div class="w-[90%] max-w-4xl pt-12 space-y-4">
    <h1 class="text-[36px] font-bold text-center">Vector Movie Search</h1>

    <app-movie-search
      [searchValue]="searchValue"
      (searchValueChange)="searchValue = $event"
      (submit)="handleSearch($event)"
    />
    <div class="flex flex-wrap gap-2 justify-center text-sm">
      @for (search of mockMovieSearches; track search) {
        <app-badge [text]="search" (badgeClicked)="searchValue = $event" />
      }
    </div>
  </div>

  <!-- Results Section -->
  <div class="w-[90%] h-full max-w-6xl">
    @if (isLoading) {
      <h1 class="text-lg font-medium text-center mt-10">Loading...</h1>
    } @else {
      @if (movies.length > 0) {
        <h2 class="text-2xl font-bold py-5">Matching Movies</h2>
        <swiper-container
          slides-per-view="4.5"
          navigation="false"
          pagination="false"
          space-between="30"
          loop="false"
          class="w-full"
        >
          @for (movie of movies; track movie.id) {
            <swiper-slide>
              <app-movie-card [movie]="movie" />
            </swiper-slide>
          }
        </swiper-container>
      }
    }
  </div>
</div>
